### ISSUE TITLE
Feature - Web Delivery Design Override

### ISSUE THREAD

**Issue by bakome** [forward-distribution/bridget#4]
## Preface
The FP app will load very different and tailored designs from multiple consumers, and because of that various problems regarding design can emerge. There should be a way for some designs to be fixed from inside the consumer delivery for the FP app without affecting regular browser web delivery.

## Problem statement
Design override in current implementation from the Delivery is impossible. There is no way we can distinguish if the app is loaded in browser or the FP app.

## Why
No matter how perfect the designs can be, there will be always small issues that will pop up, like designs tailored specific to some web browser or some third party integration that can interfere and broke some styles. Also  this feature will provide us with ability to even more customize the FP app for the consumer.

## How
With a simple addition of one main class to the body element in webview. 
Ex. `fp-bridget__webview`

After the addition we can catch this class and create tailored design for the FP app.
Ex. `.fp-bridget__webview .some-specific-class { styles }`

## What could go wrong
Because we are using the standard html class features there will be no side effects in the app or the delivery, of course this will depend a lot from the delivery implementation. They should always avoid using that main FP app class for anything else.

**Comment by andon** [comment]
The fix from #6 was not working properly. There is a workaround in #7
