### ISSUE TITLE
Provide minified JavaScript bundle

### ISSUE THREAD

**Issue by oliverlaz** [forward-distribution/bridget#5]
Currently, bridget serves unminified JavaScript code towards end users (adding around 55k of JavaScript to be downloaded and parsed).
I think for production use, the package should also include a minified version.

**Comment by filipboev** [comment]
> Currently, bridget serves unminified JavaScript code towards end users (adding around 55k of JavaScript to be downloaded and parsed). I think for production use, the package should also include a minified version.

Hey @oliverlaz , you can use the [minified version](https://unpkg.com/@forward-distribution/bridget@1.4.0/dist/bridget.min.js) in unpkg. Currently the unminified version is referenced [here](https://github.com/forward-distribution/bmg-delivery-web/pull/453/files#diff-89d8094afb348c6f1216a4172a6a28ed9b97f9f223ca1077dccebce4d630adc3R87).
